### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by a8655099449** [xcatliu/pagic#100]
运行安装代码时报错
```
deno install --unstable --allow-read --allow-write --allow-net --allow-run --name=pagic https://deno.land/x/pagic/mod.ts
```

![image](https://user-images.githubusercontent.com/58685483/150752096-1908e52c-b6a0-4074-a752-4967c26de8fa.png)

好像是某个包不支持引用了 [htmlparser](https://dev.jspm.io/npm:htmlparser2@4?dew)

**Comment by lovefengruoqing** [comment]
same problem!

**Comment by a8655099449** [comment]
现在已经可以安装了
