### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by rainzee** [xcatliu/pagic#103]
![image](https://user-images.githubusercontent.com/4585440/159797022-ae710878-1020-4f6b-b1d5-657486555c58.png)

**Comment by justjavac** [comment]
我刚试了一下，使用最新版 deno，可以正常安装

**Comment by rainzee** [comment]
我用--reload可以安装了，但是弹出一个警告，不支持request框架，这个警告可以无视吗？

**Comment by justjavac** [comment]
截个图，我这儿没有警告啊

**Comment by rainzee** [comment]
<img width="748" alt="截屏2022-03-28 下午8 48 09" src="https://user-images.githubusercontent.com/4585440/160401249-012a78c7-404c-4a74-8a4e-34030db993e7.png">

**Comment by justjavac** [comment]
这个没事儿，因为 Deno 暂时还不支持 `requestAnimationFrame`，所以 React 使用了 polyfill 的方案

**Comment by onesmail** [comment]
![image](https://user-images.githubusercontent.com/9582449/164952366-52c38ccf-3457-4dc1-a90a-1a085e075432.png)
我在windows下安装成功后运行，报上图的错，为什么呢？

**Comment by justjavac** [comment]
没有配置文件吧

**Comment by onesmail** [comment]
![image](https://user-images.githubusercontent.com/9582449/164953006-92b29dac-2781-4975-a51d-97cd9cf7ec87.png)
是我截图里的配置文件吗？

**Comment by justjavac** [comment]
双引号去掉

```ts
export default {};
```

**Comment by onesmail** [comment]
谢谢，犯了低级错误:sweat_smile:，已经决绝，可以正常运行:thumbsup:。

**Comment by gaxuhongyu** [comment]
mac安装报错呢：
```shell
local@mac:~/deno|⇒  deno install --unstable --allow-read --allow-write --allow-net --allow-run --name=pagic https://deno.land/x/pagic@v1.5.1/mod.ts
Download https://dev.jspm.io/npm:uc.micro@1?dew
Download https://dev.jspm.io/npm:uc.micro@1/properties/Any/regex?dew
Download https://dev.jspm.io/npm:domelementtype@1?dew
Download https://dev.jspm.io/npm:buffer-from@1?dew
Download https://dev.jspm.io/npm:string_decoder@1?dew
Download https://dev.jspm.io/npm:util-deprecate@1?dew
error: Import 'https://dev.jspm.io/npm:domelementtype@1?dew' failed: 500 Internal Server Error
    at https://dev.jspm.io/npm:domhandler@2.4.2/index.dew.js:1:50
```

**Comment by xcatliu** [comment]
@gaxuhongyu  500 估计是服务端挂了，稍等再重试吧，或者挂梯子

**Comment by drizzlesconsin** [comment]
```ts
error: Import 'https://dev.jspm.io/npm:uc.micro@1/properties/Any/regex?dew' failed: 500 Internal Server Error
```
https://dev.jspm.io/npm:uc.micro@1/properties/Any/regex
**提示: Internal error on package lookup.**

@xcatliu 跟楼上是一样的问题，这个要怎么解。

**Comment by newwan** [comment]
> ```ts
> error: Import 'https://dev.jspm.io/npm:uc.micro@1/properties/Any/regex?dew' failed: 500 Internal Server Error
> ```
> 
> https://dev.jspm.io/npm:uc.micro@1/properties/Any/regex **提示: Internal error on package lookup.**
> 
> @xcatliu 跟楼上是一样的问题，这个要怎么解。

外网vps测试也是同样的问题，有大佬解决了没

**Comment by tianyu666** [comment]
https://dev.jspm.io/npm:buffer-from@1?dew
https://dev.jspm.io/npm:util-deprecate@1?dew
https://dev.jspm.io/npm:uc.micro@1?dew
https://dev.jspm.io/npm:domelementtype@1?dew
https://dev.jspm.io/npm:uc.micro@1/properties/Any/regex?dew
https://dev.jspm.io/npm:string_decoder@1?dew

上面这些包都不见了？

**Comment by tianyu666** [comment]
> 

用这个地址吧，我修改了一下新打的包。https://deno.land/x/tianyu_pagic@1.0.0/mod.ts

**Comment by xcatliu** [comment]
jspm 应该已经修复了 dev.jspm.io 无法访问的问题，我已经亲测可安装了
