### ISSUE TITLE
[install] some package can't import

### ISSUE THREAD

**Issue by tianyu0904** [xcatliu/pagic#106]
https://dev.jspm.io/npm:buffer-from@1?dew
https://dev.jspm.io/npm:util-deprecate@1?dew
https://dev.jspm.io/npm:uc.micro@1?dew
https://dev.jspm.io/npm:domelementtype@1?dew
https://dev.jspm.io/npm:uc.micro@1/properties/Any/regex?dew
https://dev.jspm.io/npm:string_decoder@1?dew

**Comment by tianyu666** [comment]
请尝试将dev.jspm.io替换为 jsom.dev

**Comment by xcatliu** [comment]
jspm 应该已经修复了 dev.jspm.io 无法访问的问题。
