### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by gastrodia** [xcatliu/pagic#108]
![image](https://user-images.githubusercontent.com/96605737/193185599-2988cb35-5c39-4043-b17a-4d7b4be8f560.png)
![image](https://user-images.githubusercontent.com/96605737/193185654-9a51e744-8003-4f3e-b7b5-3906f3f7287e.png)

**Comment by gastrodia** [comment]
![image](https://user-images.githubusercontent.com/96605737/193186215-d0e16c03-06aa-4f1d-a90c-dba5184a199c.png)

这个包是cdn证书过期了好像

**Comment by xcatliu** [comment]
cdn 过期的问题已解决（旧域名服务商不支持更新 caa 记录，转移了域名服务商）
