### ISSUE TITLE
pagic build报错 Uncaught TypeError: ext[key].bind is not a function

### ISSUE THREAD

**Issue by sjxhgjxf** [xcatliu/pagic#109]
**Describe the bug**
<img width="647" alt="image" src="https://user-images.githubusercontent.com/8445821/203503718-d1be0738-b66d-4676-9c67-c164151dddf0.png">

**Context**
- Pagic version: latest(1.5.1)
- Deno version: 1.28.1

**Comment by lichangyuan1993** [comment]
> **Describe the bug** <img alt="image" width="647" src="https://user-images.githubusercontent.com/8445821/203503718-d1be0738-b66d-4676-9c67-c164151dddf0.png">
> 
> **Context**
> 
> * Pagic version: latest(1.5.1)
> * Deno version: 1.28.1

I have the same problem.

`deno 1.28.3 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.8.3
`

I just wanted to write a simple React single-page application in Pagic

**Comment by lichangyuan1993** [comment]
我也遇到了这个问题

```powershell
./deno-pagic/
├── pagic.config.ts
└── README.md

0 directories, 2 files
```

```powershell
D:\deno-workspaces\deno-pagic>pagic build --watch --serve
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
error: Uncaught TypeError: ext[key].bind is not a function
    DomUtils[key] = ext[key].bind(DomUtils);
                             ^
    at https://dev.jspm.io/npm:domutils@1.7.0!cjs:320:30
    at Array.forEach (<anonymous>)
    at https://dev.jspm.io/npm:domutils@1.7.0!cjs:319:20
    at Array.forEach (<anonymous>)
    at https://dev.jspm.io/npm:domutils@1.7.0!cjs:318:67
```

**Comment by gltjk** [comment]
我把 Pagic 的代码下到了本地安装，把 deps.ts 里所有的 `https://dev.jspm.io/` 改成了 `npm:`，搞定了。

I fixed this problem by installing from a local code base of Pagic and replacing all `https://dev.jspm.io/` with `npm:` in deps.ts.

**Comment by zhper** [comment]
这个问题有具体的解决方案了吗？
Is there a specific solution for this problem?

**Comment by zhper** [comment]
> 



> 我把 Pagic 的代码下到了本地安装，把 deps.ts 里所有的 `https://dev.jspm.io/` 改成了 `npm:`，搞定了。
> 
> I fixed this problem by installing from a local code base of Pagic and replacing all `https://dev.jspm.io/` with `npm:` in deps.ts.

你好，请问您下到本地后，后续怎么操作呢？

**Comment by xcatliu** [comment]
@zhper 已修复此问题，请安装最新版即可

```bash
deno install --unstable --allow-read --allow-write --allow-net --allow-env --allow-run --name=pagic --force https://deno.land/x/pagic@v1.6.2/mod.ts
```

**Comment by xuya227939** [comment]
`deno v1.31.1`

```
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills
error: Uncaught TypeError: ext[key].bind is not a function


@xcatliu 
```
