### ISSUE TITLE
error: Import 'https://cdn.pagic.org/i18next@19.8.1/esnext/i18next.js'

### ISSUE THREAD

**Issue by j-oi** [xcatliu/pagic#116]
**Describe the bug**

**To Reproduce**
deno install --unstable --allow-read --allow-write --allow-net --allow-env --allow-run --name=pagic https://deno.land/x/pagic@v1.6.2/mod.ts

**Expected behavior**
suppose to install successfully

**Screenshots**
 error sending request for url (https://cdn.pagic.org/i18next@19.8.1/esnext/i18next.js): error trying to connect: invalid peer certificate: Expired
    at https://deno.land/x/pagic@v1.6.2/src/plugins/i18n.tsx:4:21

**Context**
- Pagic version:  latest or https://deno.land/x/pagic@v1.6.2/mod.ts
- Deno version: v8 12.0.267.1
typescript 5.2.2
- Browser version (optional): 
- OS version: windows 11

**Comment by xcatliu** [comment]
The reason is that the SSL certificate has expired. It has now been updated.
