### ISSUE TITLE
How do I create an index.html to lists all the other pages

### ISSUE THREAD

**Issue by kasajian** [xcatliu/pagic#15]
I want to create a landing index.html page, so I create an index.md file.
Within it, I want to have a list of links to the other html files.
I'm willing to do this in JavaScript.
Can we have a variable and gets injected which is the list of the other html files?

Perhaps the easiest thing to do is to pass in the a list of files, in a hierarchy, starting with the public root folder.

**Comment by xcatliu** [comment]
Thanks for your advice, I've been thinking about adding this feature.
It will be in next version.

**Comment by xcatliu** [comment]
Use sidebar plugin and then you will get a `sidebar` props
