### ISSUE TITLE
能否打包为可执行文件 Can it be packaged as an executable like .exe?

### ISSUE THREAD

**Issue by gz222** [xcatliu/pagic#18]
node.js对我使用的电脑来说不太方便，我想把pagic放在u盘

Node.js is not very convenient for the computer I use, I want to put pagic on the u disk

**Comment by xcatliu** [comment]
貌似有一个工具可以做这件事 https://github.com/zeit/pkg
可以自行尝试下。

There is a tool can do this https://github.com/zeit/pkg
You can try it yourself.

**Comment by feng89Js** [comment]
deno已支持打包为可执行文件，但pagic因为加入了tsx会编译失败
https://github.com/denoland/deno/issues/986
