### ISSUE TITLE
还是会复制其他文件的问题

### ISSUE THREAD

**Issue by shellphon** [xcatliu/pagic#2]
当存在子目录的情况下，copyOtherFiles中glob.sync需要带上nodir配置，否则，子目录的md和_layout.js会因为拷贝目录而被带入。

```
function copyOtherFiles(srcDir, distDir) {
  const otherFiles = glob.sync('**/*', {
    ignore: [
      '**/*.md',
      '**/_*',
    ],
    nodir:true,//查了一下glob有这个避开目录的配置
    cwd: srcDir,
  });

  otherFiles.forEach(filePath => {
    const fileResolvedPath = path.resolve(srcDir, filePath);
    const distPath = path.resolve(distDir, filePath);

    fse.copySync(fileResolvedPath, distPath);

    console.log(`Generated ${distPath}`);
  });
}

```

**Comment by shellphon** [comment]
另外， require(_layout.js)的话，require有缓存，如果用了watch的话， _layout.js修改并不能实时反馈到真实模板中。（当时是在想每个md文件都要require一次layout会不会有性能问题，突然想起require的缓存）

**Comment by xcatliu** [comment]
@shellphon 感谢反馈，稍后我会修复。

**Comment by shellphon** [comment]
哈，顺带抛出多几个想法，就是
1. watch的时候貌似子目录内文件改动不会触发watch，似乎需要加入配置recursive
2. 关于require缓存的问题，在想通过判断变更时文件来删除require缓存重新require，而目前的处理方式是一旦有文件改动就会重新来一轮目录清除和文件拷贝，是否能细致到文件变更只变更对应的文件，比如静态资源则只变更静态资源的拷贝，_layout 则变更对应目录所有的md文件，特定md文件则变更特定文件。想起来貌似比较复杂。

**Comment by xcatliu** [comment]
@shellphon 已修复 `nodir: true` 的问题。
watch 的问题暂时不影响使用，以后有时间了再考虑如何修复。

顺便重构了代码，使用了 class，提取了 processors 方便以后加功能，添加了单元测试。

**Comment by xcatliu** [comment]
@shellphon v0.4.1 修复了缓存的问题。
https://github.com/xcatliu/pagic/blob/v0.4.1/src/util/getLayout.js#L16

**Comment by shellphon** [comment]
getLayout修复的缓存，好像是每次getLayout都要require么？这样require的缓存貌似就没意义了。

这个wacth和缓存，我fork后开了个分支写了实现。主要是针对md文件、layout、其他资源文件的修改变动做区分处理，当识别是layout文件修改时才做缓存删除。

https://github.com/shellphon/pagic/blob/watchfile/src/Pagic.js#L50~L127
https://github.com/shellphon/pagic/blob/watchfile/src/Pagic.js#L227~L256

**Comment by xcatliu** [comment]
@shellphon 👍 我有空会参考你的改一下。

**Comment by xcatliu** [comment]
@shellphon 已完成 watch 的问题的修复，[v0.5.0](https://github.com/xcatliu/pagic/releases/tag/v0.5.0)，现在修改文件时只会触发修改文件的 rebuild

**Comment by shellphon** [comment]
看了一下实现，现在的实现上，当修改的是layout文件时，将layout文件所在目录及子目录下的md进行重新处理，这样如果子目录已有layout文件的话，这些md重复转换了一次，而且layout每次都是重新require，缓存没有意义了。这部分你如何看待呢？

**Comment by xcatliu** [comment]
@shellphon 感谢提醒，确实还有这两个问题。第二个问题容易解决。第一个问题有点麻烦。
