### ISSUE TITLE
Let's add unit tests! 💣🐛💥

### ISSUE THREAD

**Issue by revelt** [xcatliu/pagic#21]
@xcatliu for unit tests here, if you had a magic wand and could create all missing unit tests in one swoop — what would be your preferred platform (Deno/Node) and your preferred test runner (Deno.test/Jest/Mocha/node-tap/etc) and your preferred unit test assertion style (expect, should or simply Deno's)?

Let's start with defining a wishlist spec for tests.

Native `Deno.test` would be hardcore for this project imho...

What do you think?

**Comment by xcatliu** [comment]
I prefer Deno. But if it's hard to use, Jest is ok.

**Comment by xcatliu** [comment]
All the code inside `src/utils` and `src/plugins` have been tested. 🎉

Next step is to test `src/themes`, which maybe should use `jest` to test. Because most of the code are React Components.
