### ISSUE TITLE
Cannot translate "关闭黑暗模式", when isDark

### ISSUE THREAD

**Issue by yoshixmk** [xcatliu/pagic#24]
The Markdown contents can write each other language, but cannot translate "关闭黑暗模式".

**Comment by xcatliu** [comment]
Will fix it in next version

**Comment by xcatliu** [comment]
@yoshixmk Use img instead of word.
Checkout https://ts.xcatliu.com to preview this change

**Comment by yoshixmk** [comment]
@xcatliu 谢谢!!
