### ISSUE TITLE
感觉中文开发者给项目加上中文 readme 会更好

### ISSUE THREAD

**Issue by HaujetZhao** [xcatliu/pagic#27]
有以下几点原因：

* 开发者母语是中文，用中文写文档最熟悉，表达也能更言简意赅
* 项目的国际化是个独立的软件过程，开源项目的国际化可以求助贡献者，对英文文档，在 readme 开头放上其他语言 readme 的链接即可
* 对于同母语的新访问者，上手、参与项目更快更方便。

**Comment by xcatliu** [comment]
感谢建议
会有的！1.0.0 版本比现在 README.md 中的功能增加了很多。准备做个网站做详细的说明。
进度看这里：https://github.com/xcatliu/pagic/projects/3

**Comment by xcatliu** [comment]
中文文档已完成：https://pagic.org/
