### ISSUE TITLE
pagic.config.tsx error, but pagic.config.ts worked well

### ISSUE THREAD

**Issue by hylerrix** [xcatliu/pagic#28]
**Describe the bug**

According to `pagic.config.tsx` in [TypeScript Tutorial](https://github.com/xcatliu/typescript-tutorial/blob/master/pagic.config.tsx) repo, I changed my `pagic.config.ts` file into `pagic.config.tsx`, but got this error message:

```
Warning: Invalid value for prop `href` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in a
    in li
    in ul
    in nav
    in header
    in Header
    in body
    in html
    in Layout
error: Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at ReactDOMServerRenderer.render (https://dev.jspm.io/npm:react-dom@16.13.1/cjs/react-dom-server.browser.development.dew.js:3635:23)
    at ReactDOMServerRenderer.read (https://dev.jspm.io/npm:react-dom@16.13.1/cjs/react-dom-server.browser.development.dew.js:3286:35)
    at Object.renderToString (https://dev.jspm.io/npm:react-dom@16.13.1/cjs/react-dom-server.browser.development.dew.js:3869:33)
    at write (write.tsx:17:37)
    at Pagic.runPlugins (Pagic.ts:307:13)
    at async Pagic.rebuild (Pagic.ts:193:5)
    at async Pagic.build (Pagic.ts:130:5)
```

**To Reproduce**

https://github.com/hylerrix/deno-tutorial/blob/master/pagic.config.ts

```
deno run --unstable --allow-read --allow-write --allow-net --allow-env https://deno.land/x/pagic@0.7.28/mod.ts build --serve --watch
```

**Expected behavior**

Expected to be run well.

**Screenshots**

![](https://user-images.githubusercontent.com/19285461/86724203-28f62b80-c05b-11ea-8afd-c7ddd8e3b274.png)

**Context**
- Pagic version: 0.7.28
- Deno version: 1.1.3
- Browser version (optional): 
- OS version: MacOS Catalina 10.15.5 Beta (19F83c)

**Others**

* My `pagic.config.tsx` full to see: https://github.com/hylerrix/deno-tutorial/blob/master/pagic.config.tsx
* My Github Actions failed reason: https://github.com/hylerrix/deno-tutorial/actions/runs/160248535

**Comment by xcatliu** [comment]
Please update your `pagic.config.tsx` like this:

![image](https://user-images.githubusercontent.com/5453359/86729973-9f495c80-c060-11ea-9026-fad38b0d32a2.png)

I'll fix these two bugs in the next version.

**Comment by xcatliu** [comment]
`ignore` renamed to `exclude`, and accept `glob[]`
`nav` is not changed. `nav` is designed to not accept string as an item
