### ISSUE TITLE
没有命令可以直接生成一个基本 demo 吗？

### ISSUE THREAD

**Issue by hustcc** [xcatliu/pagic#3]
比如 `pagic init` 就生成一个基本的代码结构，然后有生成出来的 html，可以预览效果。

就像 gitbook 新建一本书的时候，会有一个 demo 书籍的基本结构。

**Comment by xcatliu** [comment]
感谢建议，会在下个版本添加此功能。

**Comment by hustcc** [comment]
好的，期待，最近准备试试，做做备忘…

**Comment by xcatliu** [comment]
已完成，请看 [README.md # pagic init](https://github.com/xcatliu/pagic#init)
新版本 v0.4.0
