### ISSUE TITLE
按照官网首页给的三行命令，启动项目了，但是乱码

### ISSUE THREAD

**Issue by vearvip** [xcatliu/pagic#38]
```js
# 安装 pagic
deno install --unstable --allow-read --allow-write --allow-net --name=pagic https://deno.land/x/pagic/mod.ts

# 创建 pagic.config.ts 和 README.md
mkdir site && cd site && echo "export default {};" > pagic.config.ts && echo "# Hello world" > README.md

# 运行 pagic
pagic build --watch --serve
```
[](url)

**Comment by vearvip** [comment]
![运行后helloworld乱码的图片](https://s1.ax1x.com/2020/08/20/d3RpqK.png)
https://s1.ax1x.com/2020/08/20/d3RpqK.png

**Comment by vearvip** [comment]
pagic v0.8.6
deno 1.3.0
v8 8.6.334
typescript 3.9.7
win10 1909

powershell version：
Major  Minor  Build  Revision
5         1          18362  752

**Comment by xcatliu** [comment]
dist 目录下的 index.html 内容正常吗？

**Comment by vearvip** [comment]
> dist 目录下的 index.html 内容正常吗？
index.html内容不正常
![img](https://s1.ax1x.com/2020/08/20/d3Xiod.png)
https://s1.ax1x.com/2020/08/20/d3Xiod.png

**Comment by xcatliu** [comment]
估计是 markdown 编译的问题，我用 windows 试试

**Comment by hu-qi** [comment]
> ```js
> # 安装 pagic
> deno install --unstable --allow-read --allow-write --allow-net --name=pagic https://deno.land/x/pagic/mod.ts
> 
> # 创建 pagic.config.ts 和 README.md
> mkdir site && cd site && echo "export default {};" > pagic.config.ts && echo "# Hello world" > README.md
> 
> # 运行 pagic
> pagic build --watch --serve
> ```

windows下请尝试使用bash命令行

**Comment by hu-qi** [comment]
啊啊啊，我这边又发现一个谜：
我在 PowerShell 中执行
`deno install --unstable --allow-read --allow-write --allow-net --name=pagic https://deno.land/x/pagic/mod.ts` 
安装了 pagic ，结果通过bash命令行执行 `pagic` 显示 **command not found**

而在 Powershell 中确是可用的 

![没图说个james8的对比图](https://user-images.githubusercontent.com/17986122/92361656-4ad66200-f121-11ea-8e59-df24cce33c38.png)

有这么神奇吗？Deno 好像没这个现象：
![没图说个james8的对比图](https://user-images.githubusercontent.com/17986122/92361780-83763b80-f121-11ea-98e9-4778bb33af69.png)

**Comment by MVEMCJSUNPE** [comment]
A bit late, but maybe try "/c/User/YOURUSERNAME/deno/.bin/pagic.cmd" ?

**Comment by drizzlesconsin** [comment]
@hu-qi 

需要在 `.zshrc` or `.bash_profile`设置 Deno 的环境变量 
```js
export PATH="$HOME/.deno/bin:$PATH"
``` 
```bash
# .zshrc or .bash_profile
$ vi ~/.zshrc
$ source .zshrc
```
