### ISSUE TITLE
readme 勘误

### ISSUE THREAD

**Issue by shellphon** [xcatliu/pagic#4]
将pagic当做module来用的内容描述上

1. 两份代码里的require都写成了 requrie

2. 第一部分代码有误
~~~
const Pagic = requrie('pagic').Pagic;

const pagic = new Pagic({
  srcDir: 'src',
  distDir: 'public',
});

pagic();
~~~

看了源码，如果用的是Pagic类，执行需要调用 `pagic.build()` ，new Pagic本身只是返回pagic实例，实例不是function，直接运行此实例代码会报错……

另外问下，将watch抽离出module，那watch只能是全局模块使用了耶，不考虑放回去了么？

**Comment by xcatliu** [comment]
@shellphon 感谢勘误~
watch 的问题是因为一开始代码写的比较乱，就没有把 watch 写到 Pagic 类里。
后面我会参考 https://hexo.io/api/ 重新设计一下 API
