### ISSUE TITLE
安装pagic报错

### ISSUE THREAD

**Issue by chentong106140** [xcatliu/pagic#41]
Powershell环境下，Deno安装成功了，开始安装pagic后报错，报错如下图片
![图片](https://user-images.githubusercontent.com/31431377/92363407-08625480-f124-11ea-880d-85d7be5c2c68.png)

麻烦帮忙看下是什么原因？

**Comment by vearvip** [comment]
hosts 配一下
199.232.68.133 raw.githubusercontent.com

**Comment by chentong106140** [comment]
> 
> 
> hosts 配一下
> 199.232.68.133 raw.githubusercontent.com

感谢

**Comment by doodlewind** [comment]
This also works for unix shell (as long as local HTTP proxy exists):

``` bash
export http_proxy=http://127.0.0.1:xxxx
export https_proxy=http://127.0.0.1:xxxx
```
