### ISSUE TITLE
运行时用缓存加速，--watch 优化等 Bug

### ISSUE THREAD

**Issue by hylerrix** [xcatliu/pagic#42]
引用一下 js-history-cn 下的用户体验问题  [jshistory-cn/pull/18#issuecomment-699835007](https://github.com/doodlewind/jshistory-cn/pull/18#issuecomment-699835007)，提出了如下需求：

* 直接点击链接无法正确跳转参考文献、脚注、术语表等 anchor，除非 cmd+click 新开页面。现在的 GitHub 默认版有加了 anchor.js，也可能是路由的问题？
* 可以正常 pagic build --serve，但 pagic build --serve --watch 报错（见下）
* 为什么纯静态站点还会依赖 React 全家桶呢？测试了不带图片纯静态的 Part-3，它的请求数量从线上的 4 个增加到了 72 个，实在有些夸张了
* build 时似乎没有缓存？没有用过 VuePress，不过看日志每次 build 都有很多 download 操作，比 hexo 还是慢了很多。这属于 Deno 的设计哲学吗？

看看方便解决嘛？计划在哪个版本里解决呢？祝 Pagic 更好！🤡

**Context**
- Pagic version: 0.9.1
- Deno version: 1.3.3
- Browser version (optional): 
- OS version: macOs 11

**Comment by xcatliu** [comment]
@hylerrix @doodlewind

> 直接点击链接无法正确跳转参考文献、脚注、术语表等 anchor，除非 cmd+click 新开页面。现在的 GitHub 默认版有加了 anchor.js，也可能是路由的问题？

已有 issue，下个版本解决。

> 可以正常 pagic build --serve，但 pagic build --serve --watch 报错（见下）

下个版本解决。

> 为什么纯静态站点还会依赖 React 全家桶呢？测试了不带图片纯静态的 Part-3，它的请求数量从线上的 4 个增加到了 72 个，实在有些夸张了

因为页面是 SPA 的，所以页面加载时需要用 React 重新渲染一遍：

> 值得注意的是，每一个由 Pagic 生成的页面都带有预渲染好的 HTML，也因此具有极致的加载性能和搜索引擎优化（SEO）。同时，一旦页面被加载，React 将接管这些静态内容，并将其转换成一个完整的单页应用（SPA），其他的页面则会只在用户浏览到的时候才按需加载。

这个功能可以[通过删除 `script` 插件去掉](https://pagic.org/zh-CN/docs/plugins.html#%E5%86%85%E7%BD%AE%E6%8F%92%E4%BB%B6)，这样的话就不是 SPA 了，也不会加载运行 React 脚本了。

请求数有 72 个，这个已经被吐槽过了🤣，但是不影响功能。所以会在发布 1.0 之后再解决。

> build 时似乎没有缓存？没有用过 VuePress，不过看日志每次 build 都有很多 download 操作，比 hexo 还是慢了很多。这属于 Deno 的设计哲学吗？

缓存问题发布 1.0 之后再优化吧。

**Comment by xcatliu** [comment]
上线了 cdn.pagic.org 域名，存储了一些打包好的第三方资源，将 70 多个请求降低到了 30 个了，适用于 `v0.9.8` 以上版本。
只有第一次 build 时会 download，下一次会读缓存。
