### ISSUE TITLE
Pagic.org public website "flashes" and then disappears 

### ISSUE THREAD

**Issue by shah** [xcatliu/pagic#46]
**Describe the bug**
Go to `pagic.org` to see the main website - on Windows 10 Pro 2004 Chrome and Edge Chromium, the site flashes and then disappears (seems the main DOM elememtn is fully hidden). 

**To Reproduce**
Go to `pagic.org` to see the main website

**Expected behavior**
Should see the website :-)

**Screenshots**
N/A

**Context**
- Pagic version: ?
- Deno version: ?
- Browser version (optional): Chrome and Edge Chromium (tried both, same behavior)
- OS version: Windows 10 Pro 2004

**Comment by xcatliu** [comment]
Thanks for your report. This should fixed now, please try again

**Comment by shah** [comment]
Indeed, it's fixed. Thanks!
