### ISSUE TITLE
Use standard Deno approach to grab themes and other assets using `mod.ts` model

### ISSUE THREAD

**Issue by shah** [xcatliu/pagic#47]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a recommendation to use standard Deno approach to grab themes and other assets using `mod.ts` and `deps.ts` models.

**Describe the solution you'd like**
In the documentation it says:

>files lists all the files of the theme, they will be "copied" to the user's project directory.

> Why is it designed like this? Why can't it traverse all the files in the theme directory automatically?

> Because Pagic needs to support an URL to configure the theme, and only one URL cannot traverse to which files are in the path. Just imagine how you can traverse https://raw.githubusercontent.com/xcatliu/pagic_theme_custom/master?

The way Deno allows a single URL to load multiple files is using `mod.ts` and exports. I suspect we can do something like that as well, but I wasn't sure how to all file types beyond *.js and *.ts. It's worth thinking about, though, to ease theme builders' burdens.

**Describe alternatives you've considered**
Use the documented method.

**Additional context**
Just trying to see if we can use as much Deno-like modules and Go-like modules.

**Comment by xcatliu** [comment]
Thanks for your advice.

Actually Pagic do use `mod.ts` as the `single URL to load multiple files`. Currently we need to export a `files` property to list all files like this:

https://github.com/xcatliu/pagic/blob/master/src/themes/docs/mod.ts

```ts
export default {
  files: [
    'assets/czs-angle-down-l.svg',
    'assets/czs-angle-up-l.svg',
    'assets/czs-github-logo.svg',
    'assets/czs-menu-l.svg',
    'assets/czs-moon.svg',
    'assets/czs-moon-l.svg',
    'assets/czs-pen.svg',
    'assets/czs-sun.svg',
    'assets/czs-sun-l.svg',
    'assets/index.css',
    'assets/prism.css',
    'assets/prism_tomorrow.css',
    'assets/reset.css',
    'assets/variables.css',
    '_footer.tsx',
    '_head.tsx',
    '_header.tsx',
    '_layout.tsx',
    '_loading.tsx',
    '_main.tsx',
    '_popover.tsx',
    '_sidebar.tsx',
    '_tools.tsx',
    '_utils.tsx',
    'favicon.ico'
  ]
};
```

There is only one property `files` now, but it can be extended in the future.

> The way Deno allows a single URL to load multiple files is using mod.ts and exports. I suspect we can do something like that as well, but I wasn't sure how to all file types beyond *.js and *.ts.


Deno only support to import `js` and `ts` files

Even if Deno supports to import  this feature, we still list all files like this list, right?

>  to ease theme builders' burdens.

Maybe we can provide a tool or a script to generate a `mod.ts` file.

**Comment by shah** [comment]
@xcatliu I _love_ this idea: "Maybe we can provide a tool or a script to generate a mod.ts file." That would ease the burdens. We are currently _heavily_ using Hugo (which we love from a speed perspective because we generate thousands of page). Hugo doesn't support  React for content generation so that's why we're evaluating Pagic.

**Comment by xcatliu** [comment]
Now you can run `pagic init` and select `site`/`theme`/`plugin` to auto generate the `pagic.config.ts` or `mod.ts`
