### ISSUE TITLE
deno安装报错

### ISSUE THREAD

**Issue by WinstonYa** [xcatliu/pagic#49]
$ deno install --unstable --allow-read=/home/xcatliu/site --allow-write=/home/xcatliu/site --allow-net --name=pagic https://deno.land/x/pagic/mod.ts
Check https://deno.land/x/pagic@v0.9.8/mod.ts
error: Existing installation found. Aborting (Use -f to overwrite).

**Comment by xcatliu** [comment]
As the error message said, you have `pagic` already installed. If you want to install the latest version to overwrite the old version, you need to use `-f` option:

```bash
deno install -f --unstable --allow-read=/home/xcatliu/site --allow-write=/home/xcatliu/site --allow-net --name=pagic https://deno.land/x/pagic/mod.ts
```
