### ISSUE TITLE
Confusing error messages

### ISSUE THREAD

**Issue by hackjutsu** [xcatliu/pagic#5]
If users run `pagic init <dir>` against an empty directory, they will get a `"<dir> is not empty"` error message. This is confusing because the directory is empty...

```bash
mkdir rogueOne
pagic init rogueOne

# failed with message "rogueOne is not empty"
``` 

Maybe a better message would be `"<dir> already exists"` in this scenario.

**Comment by xcatliu** [comment]
Thanks! Fixed, will published in next version.
