### ISSUE TITLE
Double math for latex snippet appears, with the second math not rendered correctly

### ISSUE THREAD

**Issue by MVEMCJSUNPE** [xcatliu/pagic#51]
**Describe the bug**
When I write a latex snippet in a markdown file, it is rendered TWO times, with the second rendering not rendered correctly. 

**To Reproduce**
Any math in a markdown file will have the problem: 
index.md:
$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$

**Expected behavior**
The math should be rendered once correctly. 

**Screenshots**
<img width="955" alt="pagic" src="https://user-images.githubusercontent.com/10354503/96209806-20ed3800-0f36-11eb-8396-d75a09a54b68.png">

I think it could be solved by adding a katex.min.css to "src/theme/default/assets", which will hide the mathml code and correctly style the html output, and then modifying "src/theme/default/_layout.tsx" to include katex.min.css. However, this would not correctly render math for users with their own custom _layout.tsx. 

**Context**
- Pagic version: v0.10.0
- Deno version: v1.4.5
- Browser version (optional): 81.0
- OS version: Windows 10 Home 64-bit (10.0, Build 19041)

**Comment by haohanyang** [comment]
Same on macOS
<img width="709" alt="image" src="https://user-images.githubusercontent.com/37651510/96330535-818c8a00-1088-11eb-8c1a-0c89934e7341.png">

**Comment by MVEMCJSUNPE** [comment]
Having been the one to add the math through a pull request for math, I think xcatliu just wants pagic users to manually add katex.min.css themselves. The reason why math gets rendered twice can be found in the katex documentation: [katex options](https://katex.org/docs/options.html). Since the output option is set to 'htmlAndMathml' by default, math gets rendered once in mathml and another time in html. The html math looks weird because there is no katex.min.css included by default in pagic, although we could add katex.min.css in 'src/theme/default/assets'. If we take a look at the source for xcatliu's pagic page, we see the following: 
`
const Head: PagicLayout<{
  isDark: boolean;
}> = ({ config, title, head, outputPath, contentHasKatex, isDark }) => {
  const [katexCssLoadOnce, setKatexCssLoadOnce] = React.useState(contentHasKatex);
  if (contentHasKatex && !katexCssLoadOnce) setKatexCssLoadOnce(true);
...
return (
<head>
...
{katexCssLoadOnce && (
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css"
            integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X"
            crossOrigin="anonymous"
          />
        )}
...
</head>
`
However, I think users would want katex to work out of the box rather than having to include 'katex.min.css'.

**Comment by haohanyang** [comment]
@xcatliu @MVEMCJSUNPE I recommend using Mathjax

**Comment by MVEMCJSUNPE** [comment]
Really? According to [Cocalc Blog](https://blog.cocalc.com/latex/2018/03/23/cocalc-katex.html), KaTeX seems to be faster than MathJax by a lot. Not only that, I took a look at [markdown-it-mathjax](https://www.npmjs.com/package/markdown-it-mathjax), and I'm not even sure if MathJax is available on Deno. Markdown-it-mathjax doesn't render anything, it just "converts" to LaTeX, so you would still need a MathJax module. But I haven't found any CommonJS urls that make MathJax available on Deno. Then again, I'm not that up to date with Javascript technologies, so there probably is a way to get MathJax on Deno that I'm not familiar with.

**Comment by xcatliu** [comment]
@MVEMCJSUNPE @haohanyang I got it. You are using the `default` theme which not support KaTeX yet. It will be fixed soon.

The reason I removed your code [`output: 'mathml'`](https://github.com/xcatliu/pagic/pull/50/files#diff-edc28e9bed59519506641bcf3f05e94cbbcbae70ae96262c942eed7fbfea9ebeR73) is that [Chrome does not support mathml](https://caniuse.com/mathml) while Safari do.

![image](https://user-images.githubusercontent.com/5453359/96396134-0b5b6500-11f9-11eb-93cc-dc3ef9efa205.png)

So it's necessary to set the `output` to `html` or `htmlAndMathml` and load `katex.min.css`.

**Comment by xcatliu** [comment]
Fixed in v0.10.1

**Comment by MVEMCJSUNPE** [comment]
Yeah... I didn't realize that katex.min.css was needed to get html math to render until recently. Hopefully, chromium will support MathML by the end of 2020 so external css files aren't needed. [MathML status](https://www.chromestatus.com/feature/5240822173794304)
