### ISSUE TITLE
配置工具`editOnGithub`默认指向master分支，希望兼容main分支

### ISSUE THREAD

**Issue by Sogrey** [xcatliu/pagic#59]
**Describe the bug**
我新建了一个Pagic工程，但配置功能有些问题，参考自[配置](https://pagic.org/docs/config.html#tools)
``` tsx
export default {
  tools: {
    editOnGithub: true,
    backToTop: true
  }
};
```
其中`editOnGithub`设置为`true`,点击回跳转自`master`分支，但您可能知道，现在github上新建项目主分支为`main`而不是`master`,希望能够修复，或提供配置项以兼容旧项目。谢谢。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context**
- Pagic version: 
- Deno version: 
- Browser version (optional): 
- OS version:

**Comment by xcatliu** [comment]
确实会有问题，我会改成根据当前构建的分支来决定 editOnGithub 的分支

**Comment by Sogrey** [comment]
@xcatliu tks.

**Comment by xcatliu** [comment]
@Sogrey 已在 v0.12.0 中修复

**Comment by Sogrey** [comment]
非常感谢。我使用以下命令升级pagic，亲测有效。

```
deno install -f --unstable --allow-read --allow-write --allow-net --allow-run --name=pagic https://deno.land/x/pagic@v0.12.0/mod.ts
```
