### ISSUE TITLE
类名、资源路径错误导致侧边栏 icon 不显示

### ISSUE THREAD

**Issue by phinixsdsd** [xcatliu/pagic#69]
**Describe the bug**

当我按照 [官方示例](https://pagic.cn/docs/blog.html#%E5%AF%BC%E8%88%AA%E6%A0%8F) 配置侧边栏，本地预览时 icon 显示不出来，查看控制台显示资源 404，并且 HTML 标签类名和 svg 路径前、后缀重复：

![image](https://user-images.githubusercontent.com/33592358/102013405-ee6f8800-3d8a-11eb-9233-093e53a2be2f.png)

请问这是因为 pagic 的版本更新了还是其他原因引起的？因为我看您的 blog 仓库中也是像官方文档中一样配置的，所以特来请教一下。

当我把 nav 的设置中前缀和后缀去掉，显示就正常了：

```javascript
[
    {
        text: '首页',
        link: '/',
        icon: 'home',
    },
    {
        text: '分类',
        link: '/categories/',
        icon: 'category',
    },
    {
        text: '标签',
        link: '/tags/',
        icon: 'tag',
    },
    {
        text: '关于',
        link: '/about/',
        icon: 'about',
    },
    {
        text: '归档',
        link: '/archives/',
        icon: 'box',
    },
    {
        text: '友情链接',
        link: '/links/',
        icon: 'link',
    },
],
```

**Comment by phinixsdsd** [comment]
当我将项目部署到gh-pages的时候，反而是去掉前缀的写法不显示 icon，建议修改这种预览和部署不一致的情况；另外，配置 root 属性似乎对侧边栏的链接不生效？

**Comment by xcatliu** [comment]
应该是版本问题，你升级到最新版试试吧。安装时加个 `--force`

```bash
deno install --unstable --allow-read --allow-write --allow-net --allow-run --force --name=pagic https://deno.land/x/pagic@v1.0.0/mod.ts
```

**Comment by phinixsdsd** [comment]
升级到最新版问题解决了√
