### ISSUE TITLE
Clicking a file link in sidebar makes the main content disappear

### ISSUE THREAD

**Issue by x87** [xcatliu/pagic#72]
**Describe the bug**
Clicking a link to the file in sidebar makes the page unresponsive (there is a spinner that never disappears). This feature was added in #71 

**To Reproduce**
In `pagic.config.tsx` add a new entry in the `sidebar` config:

```
            {
              text: 'Download',
              link: 'classes.db'
            }
```

where `classes.db` is a local file. Deploy the site and click the Download link. The browsers starts downloading the file and at the same time the main content is replaced with a spinner that never goes away. All links become unresponsive.

**Expected behavior**
Clicking Download link starts file downloading. The rest of the site is not affected.

**Screenshots**
![pagic bug](https://user-images.githubusercontent.com/5698288/102953746-04263100-44a0-11eb-9bc2-737cc3f962b0.PNG)

It can be seen live here: https://sannybuilder.github.io/classes/

**Context**
- Pagic version: 1.1.0
- Deno version: 1.6.1
- Browser version (optional): 
- OS version: Windows 10

**Comment by xcatliu** [comment]
Please try v1.1.1

**Comment by x87** [comment]
@xcatliu thanks, it works!
