### ISSUE TITLE
震惊!居然不支持ie浏览器?竟然没有用模块打包器吗?

### ISSUE THREAD

**Issue by masx200** [xcatliu/pagic#87]
**Describe the bug**
震惊!居然不支持ie浏览器?竟然没有用模块打包器吗?
**To Reproduce**
https://ts.xcatliu.com/
**Expected behavior**

**Screenshots**

**Context**
- Pagic version: 
- Deno version: 
- Browser version (optional): 
- OS version:

**Comment by xcatliu** [comment]
也可以理解为先进性😀 https://pagic.org/zh-CN/docs/limitations.html

**Comment by masx200** [comment]
我觉得使用webpack加babel-polyfill并不是什么难事，再说了代码压缩混淆一下不香吗

**Comment by xcatliu** [comment]
要加打包的话，估计会使用 Deno 的 `deno bundle` 功能
