### ISSUE TITLE
Build process does not finish

### ISSUE THREAD

**Issue by yoshixmk** [xcatliu/pagic#90]
**Describe the bug**

Why doesn't the build finish with a custom pagic.config.tsx?  

Tail 10 lines in log:  
```bash
...
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/_header.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/_layout.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/_loading.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/_main.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/_popover.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/_sidebar.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/_tools.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/_utils.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/blog/_archives.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/blog/_layout.js
[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/pagic.config.js
```

After write `[Pagic] Write /home/runner/work/deno-x-ranking/deno-x-ranking/dist/pagic.config.js`, stop to build.  

**To Reproduce**

Build use [examples/README.md](https://github.com/yoshixmk/deno-x-ranking/tree/develop/examples)  

I tried including the default settings below, but the result was the same outputs.

```
    plugins: ["clean", "init", "md", "tsx", "script", "layout", "out", "ga"],
    watch: false,
    serve: false,
    port: 8000,
```

**Expected behavior**

If it does not use `--serve` or `--watch`, it will exit and return code 0.

**Screenshots**

more 27 min, Endless... :)
![image](https://user-images.githubusercontent.com/6196702/129569322-a9247d2a-4747-41ac-b4d0-d77974f450f0.png)

**Context**
- Pagic version: v1.4.0 
- Deno version: 1.13.0
- Browser version (optional): -
- OS version: MacOS and Deno's docker image `denolib/setup-deno@v2`

**Comment by xcatliu** [comment]
Working on it

**Comment by uki00a** [comment]
I also encountered this problem. It reproduced with Deno v1.14, but not with v1.10.2 :thinking:

**Comment by uki00a** [comment]
Awesome! Thanks a lot @xcatliu!
